#!/bin/sh

# Checks to see if battery folders exist, if not, will exit with error
[ ! -e /sys/class/power_supply/BAT?* ] && echo "No battery found" && exit 1

# Loops through all of the batteries and formats the info
for battery in /sys/class/power_supply/BAT?*
do
	# Sets up the status and capacity
	status=$(cat "$battery/status")
	case "$status" in
		"Full") status="⚡" ;;
		"Discharging") status="🔋" ;;
		"Charging") status="🔌" ;;
		"Unknown") status="❓" ;;
	esac
	capacity=$(cat "$battery/capacity")
	# Will make a warn variable if discharging and low
	[ "$status" = "🔋" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%\n" "$warn" "$status" "$capacity"
done && return 0
